//
//  String+SceneRestorationKeys.swift
//  EVIO - WhiteLabel
//
//  Created by Tiago Moreira on 17/12/2021.
//

import Foundation

/// # EXTENSION THAT ADDS PROPERTIES THAT REPRESENT THE SCENE STORAGE KEYS TO THE SWIFT'S BUILT IN STRING STRUCT
public extension String {
    
    static let initialPage: String = "initialPage"
    static let userBlocked: String = "userBlocked"
    static let mapLocation: String = "mapLocation"
    static let mapPresentationNavigation: String = "mapPresentationNavigation"
    static let mapNavigation: String = "mapNavigation"
    static let showSearchPage: String = "showSearchPage"
    static let searchText: String = "searchText"
    static let searchLocations: String = "searchLocations"
    static let searchChargingStations: String = "searchChargingStations"
    static let connectorTypeListExpanded: String = "connectorTypeListExpanded"
    static let vehicleTypeListExpanded: String = "vehicleTypeListExpanded"
    static let parkingTypeListExpanded: String = "parkingTypeListExpanded"
    static let filterPresentation: String = "filterPresentation"
    static let filtersData: String = "filtersData"
    static let favouritesChargerData: String = "favouritesChargerData"
    static let favouritesPageToPresent: String = "favouritesPageToPresent"
    static let mapViewChargerData: String = "mapViewChargerData"
    static let chargingPointSummaryPageToPresent: String = "chargingPointSummaryPageToPresent"
    static let chargingPointSummaryNavigation: String = "chargingPointSummaryNavigation"
    static let chargingPointEnteredBackground: String = "chargingPointEnteredBackground"
    static let chargingPointDetailsEnteredBackground: String = "chargingPointDetailsEnteredBackground"
    static let chargingPointDetailsPageToPresent: String = "chargingPointDetailsPageToPresent"
    static let chargingPointDetailsNavigation: String = "chargingPointDetailsNavigation"
    static let contractsSelectionSelectedTab: String = "contractsSelectionSelectedTab"
    static let chargingPointSummaryNavigationModel: String = "chargingPointSummaryNavigationModel"
    static let chargingPointDetailsNavigationModel: String = "chargingPointDetailsNavigationModel"
    static let chargingPointSummaryData: String = "chargingPointSummaryData"
    static let chargingPointDetailsData: String = "chargingPointDetailsData"
    static let chargingPointSummaryPresentationModel: String = "chargingPointSummaryPresentationModel"
    static let chargingPointDetailsPresentationModel: String = "chargingPointDetailsPresentationModel"
    static let chargingPointDetailsSourceTypeSelected: String = "chargingPointDetailsSourceTypeSelected"
    static let chargingPointDetailsOperatorDetailsExpanded: String = "chargingPointDetailsOperatorDetailsExpanded"
    static let createAccountPageToNavigate: String = "createAccountPageToNavigate"
    static let reportIssueOptionSelected: String = "reportIssueOptionSelected"
    static let reportIssueSelectedText: String = "reportIssueSelectedText"
    static let signupViewShowActivationView: String = "signupViewShowActivationView"
    static let signupViewSheetToPresent: String = "signupViewSheetToPresent"
    static let signupViewShowPageToPresent: String = "signupViewShowPageToPresent"
    static let signupViewSourceType: String = "signupViewSourceType"
    static let signupViewUserImage: String = "signupViewUserImage"
    static let signupViewName: String = "signupViewName"
    static let signupViewEmail: String = "signupViewEmail"
    static let signupViewPhoneNumber: String = "signupViewPhoneNumber"
    static let signupViewPhoneCode: String = "signupViewPhoneNumber"
    static let signupViewEmailError: String = "signupViewEmailError"
    static let signupViewPhoneError: String = "signupViewPhoneError"
    static let signupViewPassword: String = "signupViewPassword"
    static let signupViewTermsAndConditions: String = "signupViewTermsAndConditions"
    static let signupViewServices: String = "signupViewServices"
    static let signupViewProducts: String = "signupViewProducts"
    static let signupViewMarketing: String = "signupViewMarketing"
    static let signupViewPasswordViewSheetToPresent: String = "signupViewPasswordViewSheetToPresent"
    static let signupPasswordTextFieldToggle: String = "signupPasswordTextFieldToggle"
    static let loginPass: String = "loginPass"
    static let loginPhoneNumber: String = "loginPhoneNumber"
    static let loginEmail: String = "loginEmail"
    static let loginPhoneCode: String = "loginPhoneCode"
    static let loginPageToNavigate: String = "loginPageToNavigate"
    static let loginPageSheetToPresent: String = "loginPageSheetToPresent"
    static let recoverPasswordPageEmail: String = "recoverPasswordPageEmail"
    static let recoverPasswordPageEmailError: String = "recoverPasswordPageEmailError"
    static let recoverPasswordPagePhoneNumber: String = "recoverPasswordPagePhoneNumber"
    static let recoverPasswordPagePhoneNumberError: String = "recoverPasswordPagePhoneNumberError"
    static let recoverPasswordPagePhoneCode: String = "recoverPasswordPagePhoneCode"
    static let activationPageCode: String = "activationPageCode"
    static let activationPagePassword: String = "activationPagePassword"
    static let activationPagePasswordError: String = "activationPagePasswordError"
    static let activationPageRepeatPassword: String = "activationPageRepeatPassword"
    static let activationPageRepeatPasswordError: String = "activationPageRepeatPasswordError"
    static let myAccountPagePageToNavigate: String = "myAccountPagePageToNavigate"
    static let myAccountPagePageToPresent: String = "myAccountPagePageToPresent"
    static let editAccountSheetToPresent: String = "editAccountSheetToPresent"
    static let editAccountPageToNavigate: String = "editAccountPageToNavigate"
    static let editAccontPageToPresent: String = "editAccontPageToPresent"
    static let editAccountUserImage: String = "editAccountUserImage"
    static let editAccountUserName: String = "editAccountUserName"
    static let editAccountUserEmail: String = "editAccountUserEmail"
    static let editAccountUserEmailError: String = "editAccountUserEmailError"
    static let editAccountUserPhone: String = "editAccountUserPhone"
    static let editAccountUserPhoneError: String = "editAccountUserPhoneError"
    static let editAccountUserPhoneCode: String = "editAccountUserPhoneCode"
    static let editAccountRefPlacesList: String = "editAccountRefPlacesList"
    static let changeEmailOrPhonePageEmail: String = "changeEmailOrPhonePageEmail"
    static let changeEmailOrPhonePageEmailError: String = "changeEmailOrPhonePageEmailError"
    static let changeEmailOrPhonePagePhoneNumber: String = "changeEmailOrPhonePagePhoneNumber"
    static let changeEmailOrPhonePagePhoneCode: String = "changeEmailOrPhonePagePhoneCode"
    static let changeEmailOrPhonePagePhoneNumberError: String = "changeEmailOrPhonePagePhoneNumberError"
    static let changeEmailOrPhonePageShowActivationPage: String = "changeEmailOrPhonePageShowActivationPage"
    static let changePasswordPageOldPassword: String = "changePasswordPageOldPassword"
    static let changePasswordPageNewPassword: String = "changePasswordPageNewPassword"
    static let changePasswordPageConfirmNewPassword: String = "changePasswordPageConfirmNewPassword"
    static let changePasswordPageNewPasswordError: String = "changePasswordPageNewPasswordError"
    static let changePasswordPageConfirmPasswordError: String = "changePasswordPageConfirmPasswordError"
    static let searchLocationPageSearchText: String = "searchLocationPageSearchText"
    static let chooseLocationFromMapPageShowSearchPage: String = "chooseLocationFromMapPageShowSearchPage"
    static let addOrEditReferencePlacePage: String = "addOrEditReferencePlacePage"
    static let selectContractGoToContractDetails: String = "selectContractGoToContractDetails"
    static let selectContractSelectedContract: String = "selectContractSelectedContract"
    static let contractDetailsViewPageToPresent: String = "contractDetailsViewPageToPresent"
    static let contractDetailsViewPageToNavigate: String = "contractDetailsViewPageToNavigate"
    static let joinMobieViewName: String = "joinMobieViewName"
    static let joinMobieViewAddress: String = "joinMobieViewAddress"
    static let joinMobieViewZipCode: String = "joinMobieViewZipCode"
    static let joinMobieViewCountry: String = "joinMobieViewCountry"
    static let joinMobieViewTin: String = "joinMobieViewTin"
    static let joinMobieViewMobile: String = "joinMobieViewMobile"
    static let joinMobieViewEmail: String = "joinMobieViewEmail"
    static let joinMobieViewGeneralConditions: String = "joinMobieViewGeneralConditions"
    static let joinMobieViewRemoteConditions: String = "joinMobieViewRemoteConditions"
    static let activateCardViewTin: String = "activateCardViewTin"
    static let activateCardViewEmail: String = "activateCardViewEmail"
    static let activateCardViewCardNumber: String = "activateCardViewCardNumber"
    static let evsSelectedTab: String = "evsSelectedTab"
    
}
